Repository Team-pingping/pingping-BE, pull requests merged in 2024-11, with the labels that each got.

#39 [feat] mongodb atlas로 변경
  Ping-Api/src/main/resources/application-prod.yaml
  Ping-Infra/src/main/kotlin/com/ping/infra/nonmember/domain/mongo/entity/BookmarkEntity.kt
Labels: feature

#41 [feat] rest docs를 swagger로 변환해주는 open api spec
  .gitignore
  Ping-Api/build.gradle.kts
  Ping-Api/src/docs/asciidoc/NonMember.adoc
  Ping-Api/src/docs/asciidoc/Place.adoc
  Ping-Api/src/main/kotlin/com/ping/api/global/StaticRoutingConfig.kt
  Ping-Api/src/main/resources/static/swagger/favicon-16x16.png
  Ping-Api/src/main/resources/static/swagger/favicon-32x32.png
  Ping-Api/src/main/resources/static/swagger/index.css
  Ping-Api/src/main/resources/static/swagger/index.html
  Ping-Api/src/main/resources/static/swagger/swagger-initializer.js
  Ping-Api/src/main/resources/static/swagger/swagger-ui-bundle.js
  Ping-Api/src/main/resources/static/swagger/swagger-ui-bundle.js.map
  Ping-Api/src/main/resources/static/swagger/swagger-ui-standalone-preset.js
  Ping-Api/src/main/resources/static/swagger/swagger-ui-standalone-preset.js.map
  Ping-Api/src/main/resources/static/swagger/swagger-ui.css
  Ping-Api/src/main/resources/static/swagger/swagger-ui.css.map
  Ping-Api/src/test/kotlin/com/ping/api/event/EventControllerTest.kt
  Ping-Api/src/test/kotlin/com/ping/api/global/BaseRestDocsTest.kt
  Ping-Api/src/test/kotlin/com/ping/api/nonmember/NonMemberControllerTest.kt
  Ping-Api/src/test/kotlin/com/ping/api/place/PlaceControllerTest.kt
Labels: feature, docs

#43 [feat] 비회원 랜덤 profile 생성
  Ping-Api/src/main/kotlin/com/ping/api/nonmember/NonMemberController.kt
  Ping-Api/src/test/kotlin/com/ping/api/global/BaseRestDocsTest.kt
  Ping-Api/src/test/kotlin/com/ping/api/nonmember/NonMemberControllerTest.kt
  Ping-Application/src/main/kotlin/com/ping/application/nonmember/NonMemberService.kt
  Ping-Application/src/main/kotlin/com/ping/application/nonmember/dto/GetAllNonMemberPings.kt
  Ping-Domain/src/main/kotlin/com/ping/domain/nonmember/aggregate/NonMemberDomain.kt
  Ping-Domain/src/main/kotlin/com/ping/domain/nonmember/aggregate/ProfileDomain.kt
  Ping-Domain/src/main/kotlin/com/ping/domain/nonmember/repository/ProfileRepository.kt
  Ping-Infra/src/main/kotlin/com/ping/infra/nonmember/domain/jpa/entity/NonMemberEntity.kt
  Ping-Infra/src/main/kotlin/com/ping/infra/nonmember/domain/mapper/NonMemberMapper.kt
  Ping-Infra/src/main/kotlin/com/ping/infra/nonmember/domain/mapper/ProfileMapper.kt
  Ping-Infra/src/main/kotlin/com/ping/infra/nonmember/domain/mongo/entity/ProfileEntity.kt
  Ping-Infra/src/main/kotlin/com/ping/infra/nonmember/domain/mongo/repository/ProfileMongoRepository.kt
  Ping-Infra/src/main/kotlin/com/ping/infra/nonmember/domain/repositoryImpl/ProfileRepositoryImpl.kt
Labels: feature

#47 [feat] 자동완성시 역은 우선 자동완성
  Ping-Api/src/main/kotlin/com/ping/api/place/PlaceController.kt
  Ping-Application/src/main/kotlin/com/ping/application/event/dto/CreateEvent.kt
  Ping-Application/src/main/kotlin/com/ping/application/place/PlaceService.kt
  Ping-Domain/src/main/kotlin/com/ping/domain/nonmember/aggregate/SubwayDomain.kt
  Ping-Domain/src/main/kotlin/com/ping/domain/nonmember/repository/SubwayRepository.kt
  Ping-Infra/src/main/kotlin/com/ping/infra/nonmember/domain/mapper/SubwayMapper.kt
  Ping-Infra/src/main/kotlin/com/ping/infra/nonmember/domain/mongo/entity/SubwayEntity.kt
  Ping-Infra/src/main/kotlin/com/ping/infra/nonmember/domain/mongo/repository/SubwayMongoRepository.kt
  Ping-Infra/src/main/kotlin/com/ping/infra/nonmember/domain/repositoryImpl/SubwayRepositoryImpl.kt
Labels: feature

#48 [feat] 핑 업데이트 시 업데이트 된 시간 반환
  Ping-Api/src/test/kotlin/com/ping/api/nonmember/NonMemberControllerTest.kt
  Ping-Application/src/main/kotlin/com/ping/application/event/EventService.kt
  Ping-Application/src/main/kotlin/com/ping/application/nonmember/NonMemberService.kt
  Ping-Application/src/main/kotlin/com/ping/application/nonmember/dto/GetAllNonMemberPings.kt
  Ping-Domain/src/main/kotlin/com/ping/domain/nonmember/aggregate/NonMemberUpdateStatusDomain.kt
  Ping-Domain/src/main/kotlin/com/ping/domain/nonmember/aggregate/ShareUrlDomain.kt
  Ping-Domain/src/main/kotlin/com/ping/domain/nonmember/repository/NonMemberUpdateStatusRepository.kt
  Ping-Infra/src/main/kotlin/com/ping/infra/nonmember/domain/jpa/entity/NonMemberUpdateStatusEntity.kt
  Ping-Infra/src/main/kotlin/com/ping/infra/nonmember/domain/jpa/entity/ShareUrlEntity.kt
  Ping-Infra/src/main/kotlin/com/ping/infra/nonmember/domain/jpa/repository/NonMemberUpdateStatusJpaRepository.kt
  Ping-Infra/src/main/kotlin/com/ping/infra/nonmember/domain/mapper/NonMemberUpdateStatusMapper.kt
  Ping-Infra/src/main/kotlin/com/ping/infra/nonmember/domain/mapper/ShareUrlMapper.kt
  Ping-Infra/src/main/kotlin/com/ping/infra/nonmember/domain/repositoryImpl/NonMemberUpdateStatusRepositoryImpl.kt
Labels: feature, remove

#53 [feat] ping response 변경
  Ping-Api/src/docs/asciidoc/NonMember.adoc
  Ping-Api/src/main/kotlin/com/ping/api/nonmember/NonMemberApi.kt
  Ping-Api/src/main/kotlin/com/ping/api/nonmember/NonMemberController.kt
  Ping-Api/src/test/kotlin/com/ping/api/nonmember/NonMemberControllerTest.kt
  Ping-Application/src/main/kotlin/com/ping/application/nonmember/NonMemberService.kt
  Ping-Application/src/main/kotlin/com/ping/application/nonmember/dto/CreateNonMember.kt
  Ping-Application/src/main/kotlin/com/ping/application/nonmember/dto/GetAllNonMemberPings.kt
  Ping-Application/src/main/kotlin/com/ping/application/nonmember/dto/GetNonMemberPing.kt
  Ping-Application/src/main/kotlin/com/ping/application/nonmember/dto/GetNonMemberProfile.kt
  Ping-Application/src/main/kotlin/com/ping/application/nonmember/dto/GetRecommendPings.kt
  Ping-Application/src/main/kotlin/com/ping/application/nonmember/dto/LoginNonMember.kt
  Ping-Application/src/main/kotlin/com/ping/application/nonmember/dto/UpdateNonMemberPings.kt
  Ping-Domain/src/main/kotlin/com/ping/domain/nonmember/aggregate/NonMemberDomain.kt
  Ping-Domain/src/main/kotlin/com/ping/domain/nonmember/aggregate/ProfileDomain.kt
  Ping-Infra/src/main/kotlin/com/ping/infra/nonmember/domain/jpa/entity/NonMemberEntity.kt
  Ping-Infra/src/main/kotlin/com/ping/infra/nonmember/domain/mapper/NonMemberMapper.kt
  Ping-Infra/src/main/kotlin/com/ping/infra/nonmember/domain/mapper/ProfileMapper.kt
  Ping-Infra/src/main/kotlin/com/ping/infra/nonmember/domain/mongo/entity/ProfileEntity.kt
Labels: feature

#55 [feat] 개별핑에 모든 nonMember 추가
  Ping-Application/src/main/kotlin/com/ping/application/nonmember/NonMemberService.kt
  Ping-Domain/src/main/kotlin/com/ping/domain/nonmember/repository/NonMemberRepository.kt
  Ping-Infra/src/main/kotlin/com/ping/infra/nonmember/domain/jpa/repository/NonMemberJpaRepository.kt
  Ping-Infra/src/main/kotlin/com/ping/infra/nonmember/domain/repositoryImpl/NonMemberRepositoryImpl.kt
Labels: feature

#57 [fix] 추천핑 반환 값 변경
  Ping-Api/src/test/kotlin/com/ping/api/nonmember/NonMemberControllerTest.kt
  Ping-Application/src/main/kotlin/com/ping/application/nonmember/NonMemberService.kt
  Ping-Application/src/main/kotlin/com/ping/application/nonmember/dto/GetRecommendPings.kt
Labels: fix

#61 [feat] 다른 멤버의 모핑 추가 API 구현
  Ping-Api/src/docs/asciidoc/Pings.adoc
  Ping-Api/src/main/kotlin/com/ping/api/ping/PingApi.kt
  Ping-Api/src/main/kotlin/com/ping/api/ping/PingController.kt
  Ping-Api/src/test/kotlin/com/ping/api/ping/PingControllerTest.kt
  Ping-Application/src/main/kotlin/com/ping/application/ping/dto/SaveMemberPing.kt
  Ping-Application/src/main/kotlin/com/ping/application/ping/service/PingService.kt
  Ping-Common/src/main/kotlin/com/ping/common/enums/PlaceType.kt
  Ping-Common/src/main/kotlin/com/ping/common/exception/ExceptionContent.kt
  Ping-Common/src/main/kotlin/com/ping/common/exception/GlobalExceptionHandler.kt
  Ping-Domain/src/main/kotlin/com/ping/domain/member/aggregate/NonMemberDomain.kt
  Ping-Domain/src/main/kotlin/com/ping/domain/ping/aggregate/BookmarkDomain.kt
  Ping-Domain/src/main/kotlin/com/ping/domain/ping/aggregate/NonMemberPlaceDomain.kt
  Ping-Domain/src/main/kotlin/com/ping/domain/ping/repository/BookmarkRepository.kt
  Ping-Domain/src/main/kotlin/com/ping/domain/ping/repository/NonMemberPlaceRepository.kt
  Ping-Infra/src/main/kotlin/com/ping/infra/ping/BookmarkRepositoryImpl.kt
  Ping-Infra/src/main/kotlin/com/ping/infra/ping/NonMemberPlaceRepositoryImpl.kt
  Ping-Infra/src/main/kotlin/com/ping/infra/ping/jpa/entity/NonMemberPlaceEntity.kt
  Ping-Infra/src/main/kotlin/com/ping/infra/ping/jpa/repository/NonMemberPlaceJpaRepository.kt
  Ping-Infra/src/main/kotlin/com/ping/infra/ping/mapper/NonMemberPlaceMapper.kt
  Ping-Infra/src/main/kotlin/com/ping/infra/ping/mongo/repository/BookmarkMongoRepository.kt
  Ping-Support/src/main/kotlin/com/ping/support/jwt/JwtProvider.kt
  Ping-Support/src/main/kotlin/com/ping/support/jwt/JwtUtil.kt
Labels: feature

#65 feat: #64 업종 크롤링
  Ping-Client/src/main/kotlin/com/ping/client/naver/map/NaverMapClient.kt
Labels: feature

#67 [feat] ping response에 sid 추가
  Ping-Api/src/test/kotlin/com/ping/api/ping/PingControllerTest.kt
  Ping-Application/src/main/kotlin/com/ping/application/ping/dto/GetAllNonMemberPings.kt
  Ping-Application/src/main/kotlin/com/ping/application/ping/service/PingService.kt
Labels: feature

#70 [docs] 리드미 api 명세서 최신화
  Ping-Api/src/test/kotlin/com/ping/api/member/AuthControllerTest.kt
  Ping-Application/build.gradle.kts
  README.md
Labels: docs
